config/routes.rb
ProviderProfile::Application.routes.draw do

  resources :approviders
  
  get "approviders/new"

  root :to => 'first_pages#home'

  get "first_pages/home"

  get "first_pages/about"

end

app/models/approvider.rb
# == Schema Information
#
# Table name: approviders
#
#  id           :integer          not null, primary key
#  first_name   :string(255)
#  last_name    :string(255)
#  name_appears :string(255)
#  title        :string(255)
#  philosophy   :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Approvider < ActiveRecord::Base
  attr_accessible :first_name, 
                  :last_name, 
                  :name_appears, 
                  :title, 
                  :philosophy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :name_appears, presence: true
  validates :title, presence: true
  validates :philosophy, presence: true

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/approviders_controller.rb
class ApprovidersController < ApplicationController
  
  def show
  	@approvider = Approvider.find(params[:id])
  end

  def new
  	@approvider = Approvider.new
  end

  def create
  	@approvider = Approvider.new(params[:approvider])
  	if @approvider.save
  		redirect_to @approvider
  	else
  		render 'new'
  	end
  end

  def edit
    @approvider = Approvider.find(params[:id])
  end

  def update
  	@approvider = Approvider.find(params[:id])
  	if @approvider.update_attributes(params[:approvider])
  		redirect_to @approvider
  	else
  		render 'edit'
  	end
  end




end

app/controllers/first_pages_controller.rb
class FirstPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/approviders_helper.rb
module ApprovidersHelper
end

app/helpers/first_pages_helper.rb
module FirstPagesHelper
end

app/views/approviders/edit.html.erb
<% provide(:title, 'Edit your profile') %>
<h1>Update your provider profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@approvider) do |f| %>
       <%= render 'shared/error_messages' %>

    	<%= f.label :first_name %>
    	<%= f.text_field :first_name %>

    	<%= f.label :last_name %>
    	<%= f.text_field :last_name %>

    	<%= f.label :name_appears, "Your name as you would like it to appear" %>
    	<%= f.text_field  :name_appears %>

    	<%= f.label :title %>
    	<%= f.text_field :title %>   	

    	<%= f.label :philosophy %>
    	<%= f.text_field :philosophy %>
       <br/>
    	<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
 </div>

app/views/approviders/new.html.erb
<% provide(:title, 'Create your profile') %>
<h1>Advanced Practice Provider</h1>
<p>Lorenm ipsum edawada I aks kshsiksdkn. Lorenm ipsum edawada I aks kshsiksdkn. Lorenm ipsum edawada I aks kshsiksdkn. Lorenm ipsum edawada I aks kshsiksdkn. Lorenm ipsum edawada I aks kshsiksdkn. Lorenm ipsum edawada I aks kshsiksdkn. Lorenm ipsum edawada I aks kshsiksdkn. Lorenm ipsum edawada I aks kshsiksdkn. Lorenm ipsum edawada I aks kshsiksdkn. Lorenm ipsum edawada I aks kshsiksdkn. </p>

<div class="row">
  
  <div class="span8 form-horizontal">
    <%= form_for(@approvider) do |f| %>

       <%= render 'shared/error_messages' %>

       <div class="control-group">
    	<%= f.label :first_name %>
        <div class="controls">
    	<%= f.text_field :first_name %>
        </div>
        </div>

        <div class="control-group">
    	<%= f.label :last_name %>
        <div class="controls">
    	<%= f.text_field :last_name %>
        </div>
        </div>


        <div class="control-group">
    	<%= f.label :name_appears, "Your name as you would like it to appear" %>
        <div class="controls">
    	<%= f.text_field  :name_appears %>
        </div>
        </div>

    	<div class="control-group">
        <%= f.label :title %>
        <div class="controls">
    	<%= f.text_field :title %>   	
        </div>
        </div>

    	<div class="control-group">
        <%= f.label :philosophy %>
        <div class="controls">
    	<%= f.text_area(:philosophy, size: "20x4")  %>
        </div>
        </div>

       
       <div class="form-actions">
    	<%= f.submit "Create profile", class: "btn btn-large btn-primary" %>
       </div>
    <% end %>
  </div>
 
 </div>

app/views/approviders/show.html.erb
<h2>Thanks <%=  @approvider.first_name %> for your submission.</h2>


<p><b>Your name:</b> <%=@approvider.name_appears %></p>
<p><b>Title:</b> <%=@approvider.title %> </p>
<p><b>Philosophy: </b><%=@approvider.philosophy %> </p>


<%= link_to "Edit Your Profile", edit_approvider_path(@approvider.id), class: "btn btn-large btn-primary" %>

app/views/first_pages/about.html.erb
<h1>FirstPages#about</h1>
<p>Find me in app/views/first_pages/about.html.erb</p>

app/views/first_pages/home.html.erb
<% provide(:title, "Provider Profiles") %>

<div class="center hero-unit">
<h1>SCCA Website Marketing</h1>
<p>Use these pages to supply the SCCA marketing group with up-to-date information about yourself and your work at SCCA. The information you provide here will then be loaded onto your profile page on the SCCA website. This process usually takes a couple of days.</p>

<%= link_to "AP Provider Form", new_approvider_path, class: "btn btn-large btn-primary" %>

<%= link_to "Physician Form", '#', class: "btn btn-large btn-primary" %>

</div>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top">
  	<div class="navbar-inner">
  	  <div class="container">
  	  	<%= link_to "Seattle Cancer Care Alliance Marketing", '#', id: "logo" %>
  	  	<nav>
  	  	  <ul class="nav pull-right">
  	  	  	<li> <%= link_to "Home", root_path %></li>
  	  	  	<li> <%= link_to "APP Form", new_approvider_path %></li>
  	  	  	<li> <%= link_to "Physician Form", '#' %></li>
  	  	  </ul>
  	  	</nav>
  	  </div>
  	</div>
  </header>

app/views/layouts/_shim.html.erb
  <!--if lt IE 9>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js">
  </script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SCCA Marketing | <%= yield(:title) %> </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">

  <%= yield %>

  <%= debug(params) if Rails.env.development? %>

</div>


</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @approvider.errors.any? %>
<div class="controls">
  <div id="error_explanation">
    <div class="alert alert-errors">
      Your submission contains <%= pluralize(@approvider.errors.count, "error") %>.
    </div>

    <ul>
    	<% @approvider.errors.full_messages.each do |msg| %>
    	<li>* <%= msg %></li>
        <% end %>
    </ul>
   </div>
 </div>

<% end %>